import os
import json
import shutil
from pathlib import Path

def run_wizard():
    print("🎹 Artist Platform Setup Wizard")
    print("================================")

    # 1. Basic Identity
    name = input("👤 Enter your Full Name: ")
    handle = input("🔗 Enter your Username/GitHub Handle: ")
    email = input("📧 Enter your Public Contact Email: ")
    jotform = input("📝 Enter your Jotform URL (or leave blank): ")

    # 2. API Keys
    print("\n🔑 API Configuration (Press Enter to skip and fill manually later)")
    keys = {
        "GEMINI_API_KEY": input("Gemini API Key: "),
        "GROQ_API_KEY": input("Groq API Key: "),
        "YOUTUBE_API_KEY": input("YouTube API Key: "),
        "SPOTIFY_CLIENT_ID": input("Spotify Client ID: "),
        "SPOTIFY_CLIENT_SECRET": input("Spotify Client Secret: "),
        "NEXT_PUBLIC_GA_ID": input("Google Analytics ID: "),
        "NEXT_PUBLIC_SITE_URL": input("Production URL (e.g., https://mysite.com): ")
    }

    # 3. Create .env.local
    with open('.env.local', 'w') as f:
        f.write("# Generated by Artist Platform Wizard\n")
        for key, value in keys.items():
            f.write(f"{key}={value}\n")
    print("\n✅ Created .env.local")

    # 4. Update Site Knowledge (AI context)
    knowledge_path = 'dictionaries/site-knowledge.json'
    if os.path.exists(knowledge_path):
        with open(knowledge_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        data['ownerName'] = name
        data['username'] = handle
        data['contactEmail'] = email
        data['jotformUrl'] = jotform
        
        with open(knowledge_path, 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=2)
        print(f"✅ Context updated in {knowledge_path}")

    # 5. Scrub Personal Blog Posts & Create Welcome Post
    print("\n🧹 Cleaning up existing blog posts...")
    posts_root = Path('app/[lang]/blog/posts')
    if posts_root.exists():
        # Languages to create a welcome post for
        locales = ['en', 'fr', 'es', 'hy', 'ar'] 
        
        for lang_dir in posts_root.iterdir():
            if lang_dir.is_dir():
                # Delete old mdx files
                for mdx in lang_dir.glob('*.mdx'):
                    mdx.unlink()
                
                # Create a fresh placeholder
                welcome_path = lang_dir / "welcome.mdx"
                with open(welcome_path, 'w', encoding='utf-8') as f:
                    f.write(f"---\ntitle: 'Welcome to my new platform'\npublishedAt: '2025-01-01'\nsummary: 'Setting up my creative space.'\n---\n\nHello! I am {name}. Welcome to my portfolio.")
        print("✅ Replaced old posts with Welcome placeholders.")

    # 6. Global Search & Replace (Name/Handle)
    # Target files where identity is hardcoded
    targets = ['app/layout.tsx', 'app/manifest.ts', 'package.json']
    for file_path in targets:
        if os.path.exists(file_path):
            with open(file_path, 'r', encoding='utf-8') as f:
                content = f.read()
            content = content.replace("Arman Ayva", name).replace("aivoarm", handle)
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(content)
            print(f"✅ Branded {file_path}")

    print("\n✨ Setup Complete! Run 'pnpm dev' to see your new site.")

if __name__ == "__main__":
    run_wizard()